<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TorneosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $torneos = [
            // Málaga
            [
                'idMunicipio' => 1,
                'nombre' => 'Copa Málaga 2025',
                'descripcion' => 'El torneo municipal de fútbol más importante de Málaga.',
                'logo' => 'logos/malaga1.png',
                'numeroEquipos' => 12,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-03-01'),
                'fechaFin' => Carbon::parse('2025-05-30'),
                'reglas' => 'Reglamento FIFA aplicado.',
                'premio' => 5000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 1,
                'nombre' => 'Torneo Relámpago Málaga',
                'descripcion' => 'Competencia corta de micro-fútbol en Málaga.',
                'logo' => 'logos/malaga2.png',
                'numeroEquipos' => 8,
                'estado' => 'inactivo',
                'tipoDeporte' => 'MICRO-FUTBOL',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-06-01'),
                'fechaFin' => Carbon::parse('2025-06-15'),
                'reglas' => 'Partidos a un solo tiempo de 20 minutos.',
                'premio' => 1500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Concepción
            [
                'idMunicipio' => 2,
                'nombre' => 'Liga Concepción',
                'descripcion' => 'Campeonato oficial de fútbol en Concepción.',
                'logo' => 'logos/concepcion1.png',
                'numeroEquipos' => 10,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'LIGUILLA',
                'fechaInicio' => Carbon::parse('2025-04-01'),
                'fechaFin' => Carbon::parse('2025-05-20'),
                'reglas' => 'Todos contra todos, ida y vuelta.',
                'premio' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 2,
                'nombre' => 'Copa Relámpago Concepción',
                'descripcion' => 'Torneo rápido en modalidad Futbol-5.',
                'logo' => 'logos/concepcion2.png',
                'numeroEquipos' => 6,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL-5',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-07-01'),
                'fechaFin' => Carbon::parse('2025-07-10'),
                'reglas' => 'Duración de partidos 30 minutos.',
                'premio' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Carcasí
            [
                'idMunicipio' => 3,
                'nombre' => 'Interbarrios Carcasí',
                'descripcion' => 'Torneo entre barrios de Carcasí.',
                'logo' => 'logos/carcasi1.png',
                'numeroEquipos' => 8,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-05-01'),
                'fechaFin' => Carbon::parse('2025-06-30'),
                'reglas' => 'Máximo 18 jugadores inscritos por equipo.',
                'premio' => 1200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 3,
                'nombre' => 'Copa Juvenil Carcasí',
                'descripcion' => 'Torneo juvenil en modalidad Futbol-8.',
                'logo' => 'logos/carcasi2.png',
                'numeroEquipos' => 10,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-8',
                'formato' => 'LIGUILLA',
                'fechaInicio' => Carbon::parse('2025-08-01'),
                'fechaFin' => Carbon::parse('2025-09-15'),
                'reglas' => 'Categoría Sub-18.',
                'premio' => 1800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Cerrito
            [
                'idMunicipio' => 4,
                'nombre' => 'Copa Cerrito',
                'descripcion' => 'Torneo oficial de fútbol 11.',
                'logo' => 'logos/cerrito1.png',
                'numeroEquipos' => 14,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-06-01'),
                'fechaFin' => Carbon::parse('2025-08-15'),
                'reglas' => 'Reglamento FIFA aplicado.',
                'premio' => 3000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 4,
                'nombre' => 'Torneo Escolar Cerrito',
                'descripcion' => 'Competencia intercolegial de micro-fútbol.',
                'logo' => 'logos/cerrito2.png',
                'numeroEquipos' => 6,
                'estado' => 'inactivo',
                'tipoDeporte' => 'MICRO-FUTBOL',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-09-01'),
                'fechaFin' => Carbon::parse('2025-09-10'),
                'reglas' => 'Partidos a un solo tiempo de 25 minutos.',
                'premio' => 700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Enciso
            [
                'idMunicipio' => 5,
                'nombre' => 'Liga Enciso Futbol-8',
                'descripcion' => 'Campeonato oficial de fútbol 8 en Enciso.',
                'logo' => 'logos/enciso1.png',
                'numeroEquipos' => 10,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL-8',
                'formato' => 'LIGUILLA',
                'fechaInicio' => Carbon::parse('2025-06-01'),
                'fechaFin' => Carbon::parse('2025-07-15'),
                'reglas' => 'Se aplicará reglamento FIFA adaptado.',
                'premio' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 5,
                'nombre' => 'Copa Enciso Relámpago',
                'descripcion' => 'Torneo corto de Futbol-5.',
                'logo' => 'logos/enciso2.png',
                'numeroEquipos' => 8,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-5',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-09-01'),
                'fechaFin' => Carbon::parse('2025-09-15'),
                'reglas' => 'Tiempo de juego reducido.',
                'premio' => 800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Guaca
            [
                'idMunicipio' => 6,
                'nombre' => 'Copa Guaca',
                'descripcion' => 'Torneo municipal en Guaca.',
                'logo' => 'logos/guaca1.png',
                'numeroEquipos' => 12,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-07-01'),
                'fechaFin' => Carbon::parse('2025-08-31'),
                'reglas' => 'Se aplican normas FIFA.',
                'premio' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 6,
                'nombre' => 'Relámpago Guaca',
                'descripcion' => 'Torneo relámpago de Futbol-5.',
                'logo' => 'logos/guaca2.png',
                'numeroEquipos' => 6,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-5',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-10-01'),
                'fechaFin' => Carbon::parse('2025-10-05'),
                'reglas' => 'Duración reducida.',
                'premio' => 500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Macaravita
            [
                'idMunicipio' => 7,
                'nombre' => 'Liga Macaravita',
                'descripcion' => 'Liga oficial de fútbol en Macaravita.',
                'logo' => 'logos/macaravita1.png',
                'numeroEquipos' => 8,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-08-01'),
                'fechaFin' => Carbon::parse('2025-09-20'),
                'reglas' => 'Máximo 20 jugadores por equipo.',
                'premio' => 2200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 7,
                'nombre' => 'Copa Juvenil Macaravita',
                'descripcion' => 'Torneo juvenil de micro-fútbol.',
                'logo' => 'logos/macaravita2.png',
                'numeroEquipos' => 10,
                'estado' => 'inactivo',
                'tipoDeporte' => 'MICRO-FUTBOL',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-10-10'),
                'fechaFin' => Carbon::parse('2025-10-25'),
                'reglas' => 'Categoría Sub-17.',
                'premio' => 900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Molagavita
            [
                'idMunicipio' => 8,
                'nombre' => 'Copa Molagavita',
                'descripcion' => 'Torneo municipal en Molagavita.',
                'logo' => 'logos/molagavita1.png',
                'numeroEquipos' => 14,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-07-15'),
                'fechaFin' => Carbon::parse('2025-09-30'),
                'reglas' => 'Formato tradicional.',
                'premio' => 2800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 8,
                'nombre' => 'Relámpago Molagavita',
                'descripcion' => 'Torneo relámpago intercolegial.',
                'logo' => 'logos/molagavita2.png',
                'numeroEquipos' => 6,
                'estado' => 'inactivo',
                'tipoDeporte' => 'MICRO-FUTBOL',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-11-01'),
                'fechaFin' => Carbon::parse('2025-11-05'),
                'reglas' => 'Partidos únicos.',
                'premio' => 600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // San Andrés
            [
                'idMunicipio' => 9,
                'nombre' => 'Liga San Andrés',
                'descripcion' => 'Liga oficial en San Andrés.',
                'logo' => 'logos/sanandres1.png',
                'numeroEquipos' => 12,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-08-15'),
                'fechaFin' => Carbon::parse('2025-10-30'),
                'reglas' => 'Formato ida y vuelta.',
                'premio' => 3200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 9,
                'nombre' => 'Relámpago San Andrés',
                'descripcion' => 'Torneo de Futbol-5.',
                'logo' => 'logos/sanandres2.png',
                'numeroEquipos' => 8,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-5',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-11-15'),
                'fechaFin' => Carbon::parse('2025-11-20'),
                'reglas' => 'Partidos únicos.',
                'premio' => 700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // San José de Miranda
            [
                'idMunicipio' => 10,
                'nombre' => 'Copa San José',
                'descripcion' => 'Torneo municipal en San José de Miranda.',
                'logo' => 'logos/sanjose1.png',
                'numeroEquipos' => 10,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-09-01'),
                'fechaFin' => Carbon::parse('2025-10-31'),
                'reglas' => 'Se aplican reglas FIFA.',
                'premio' => 2100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 10,
                'nombre' => 'Relámpago San José',
                'descripcion' => 'Torneo rápido de micro-fútbol.',
                'logo' => 'logos/sanjose2.png',
                'numeroEquipos' => 6,
                'estado' => 'inactivo',
                'tipoDeporte' => 'MICRO-FUTBOL',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-12-01'),
                'fechaFin' => Carbon::parse('2025-12-05'),
                'reglas' => 'Duración reducida.',
                'premio' => 400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // San Miguel
            [
                'idMunicipio' => 11,
                'nombre' => 'Liga San Miguel',
                'descripcion' => 'Liga anual en San Miguel.',
                'logo' => 'logos/sanmiguel1.png',
                'numeroEquipos' => 14,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-09-15'),
                'fechaFin' => Carbon::parse('2025-12-01'),
                'reglas' => 'Todos contra todos.',
                'premio' => 2600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 11,
                'nombre' => 'Copa Escolar San Miguel',
                'descripcion' => 'Competencia intercolegial Futbol-8.',
                'logo' => 'logos/sanmiguel2.png',
                'numeroEquipos' => 8,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-8',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-12-10'),
                'fechaFin' => Carbon::parse('2025-12-20'),
                'reglas' => 'Partidos a eliminación directa.',
                'premio' => 800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Capitanejo
            [
                'idMunicipio' => 12,
                'nombre' => 'Liga Capitanejo',
                'descripcion' => 'Liga oficial de fútbol en Capitanejo.',
                'logo' => 'logos/capitanejo1.png',
                'numeroEquipos' => 12,
                'estado' => 'activo',
                'tipoDeporte' => 'FUTBOL',
                'formato' => 'FASE_GRUPOS',
                'fechaInicio' => Carbon::parse('2025-10-01'),
                'fechaFin' => Carbon::parse('2025-12-15'),
                'reglas' => 'Formato ida y vuelta.',
                'premio' => 2300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idMunicipio' => 12,
                'nombre' => 'Copa Relámpago Capitanejo',
                'descripcion' => 'Torneo corto de Futbol-5.',
                'logo' => 'logos/capitanejo2.png',
                'numeroEquipos' => 6,
                'estado' => 'inactivo',
                'tipoDeporte' => 'FUTBOL-5',
                'formato' => 'ELIMINACION_DIRECTA',
                'fechaInicio' => Carbon::parse('2025-12-20'),
                'fechaFin' => Carbon::parse('2025-12-25'),
                'reglas' => 'Duración reducida.',
                'premio' => 600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('torneos')->insert($torneos);
    }
}
